modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = "https://github.com/terkonridge/oritech-steel-tools/issues"
license = "Creative Commons Zero v1.0 Universal"

[[mods]]
modId = "oritech_steel_tools"
version = "${version}"
displayName = "Oritech Steel Tools"
authors = "terkonridge"
description = '''
This mod adds a set of steel tools that can be crafted and recycled using Oritech materials and mechanisms.
'''
#logoFile = ""

[[dependencies.oritech_steel_tools]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.oritech_steel_tools]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.oritech_steel_tools]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "oritech_steel_tools.mixins.json"
